export const PARQUES = [
  {
    zona: 3,
    parque: "Parque San Francisco de Asís",
    direccion: "7a avenida final y 39 calle zona 3",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-san-francisco-de-asis/",
    imagen: "ParqueSanFranciscoDeAsis.jpg",
  },
  {
    zona: 4,
    parque: "Calle Peatonal",
    direccion: "Vía 5 Ruta 2 y 3 zona 4",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/calle-peatonal-4-norte/",
    imagen: "CallePeatonal.jpg",
  },
  {
    zona: 7,
    parque: "Parque Ecológico Sakerty II",
    direccion: "33 avenida A 35 calle B Colonia Sakerty II zona 7",
    tipo: "Parque Ecológico",
    link: "https://grandistritoverde.com.gt/park/parque-bethania-sakerty-ii/",
    imagen: "ParqueEcologicoSakertyII.jpg",
  },
  {
    zona: 7,
    parque: "Parque Kaminal Juyú 1",
    direccion: "23 avenida 6-75 Kaminal Juyú zona 7",
    tipo: null,
    link: null,
    imagen: "ParqueKaminalJuyu1.jpg",
  },
  {
    zona: 7,
    parque: "Parque Tikal II",
    direccion: "8va. calle y 34 avenida Colonia Tikal II zona 7",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-tikal-ii/",
    imagen: "ParqueTikalII.jpg",
  },
  {
    zona: 9,
    parque: "Plaza España",
    direccion: "7ma avenida 12 calle zona 9",
    tipo: "Espacio Patrimonial",
    link: "https://grandistritoverde.com.gt/park/plaza-espana/",
    imagen: "PlazaEspana.jpg",
  },
  {
    zona: 10,
    parque: "Parque La Villa",
    direccion: "15 avenida y 18 calle zona 10",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-la-villa/",
    imagen: "ParqueLaVilla.jpg",
  },
  {
    zona: 15,
    parque: "Rotonda VH II",
    direccion: "1era. calle 18 Av. \"A\" zona 15 VH II",
    tipo: null,
    link: null,
    imagen: "RotondaVHII.jpg",
  },
  {
    zona: 16,
    parque: "Parque Santa Rosita",
    direccion:
      "Entre 4ta. y 5ta. calle, entre 5ta. y 6ta.av. Santa Rosita zona 16",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-santa-rosita/",
    imagen: "ParqueSantaRosita.jpg",
  },
  {
    zona: 1,
    parque: "Parque Las Victorias",
    direccion: "21 avenida y 2da calle, zona 1",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/las-victorias/",
    imagen: "ParqueLasVictorias.jpg",
  },
  {
    zona: 1,
    parque: "Parque San Sebastían",
    direccion: "6ta. avenida entre 2da. y 3ra. calle zona 1",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-san-sebastian/",
    imagen: "ParqueSanSebastian.jpg",
  },
  {
    zona: 2,
    parque: "Parque Minerva",
    direccion: "6ta. avenida y 12 calle Hipodromo del Norte 6-96 zona 2",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-minerva/",
    imagen: "ParqueMinerva.jpg",
  },
  {
    zona: 5,
    parque: "Parque Navidad",
    direccion: "32 avenida y 30 calle zona 5",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-navidad/",
    imagen: "ParqueNavidad.jpg",
  },
  {
    zona: 6,
    parque: "Parque La Ceiba",
    direccion: "17 avenida 24-06 Colonia Proyectos 4-3 zona 6",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-la-ceiba/",
    imagen: "ParqueLaCeiba.jpg",
  },
  {
    zona: 6,
    parque: "Parque Barrio San Antonio",
    direccion: "15 calle 22-81 zona 6",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-barrio-san-antonio-la-amistad/",
    imagen: "ParqueBarrioSanAntonio.jpg",
  },
  {
    zona: 8,
    parque: "Parque Guarda Viejo",
    direccion: "7ma avenida 39-60 Cantón Guarda Viejo zona 8",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/guarda-viejo/",
    imagen: "ParqueGuardaViejo.jpg",
  },
  {
    zona: 11,
    parque: "Parque Mirador I",
    direccion: "20 avenida y 2da. calle Colonia Mirador I zona 11",
    tipo: null,
    link: null,
    imagen: "ParqueMiradorI.jpg",
  },
  {
    zona: 11,
    parque: "Parque Las Casuarinas",
    direccion: "Área Deportiva Colonia Granai Townson 3 zona 11",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-las-casuarinas/",
    imagen: "ParqueLasCasuarinas.jpg",
  },
  {
    zona: 12,
    parque: "Plaza Cívica El Buen Pastor",
    direccion: "Avenida Petapa 15 calle zona 12",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/plaza-civica-del-buen-pastor/",
    imagen: "PlazaCivicaElBuenPastor.jpg",
  },
  {
    zona: 13,
    parque: "Parque Deportivo y Recreativo",
    direccion: "24 y 25 calle, final Av. Las Américas y 16 Av. zona 13",
    tipo: null,
    link: null,
    imagen: null,
  },
  {
    zona: 14,
    parque: "Parque San Judas Tadeo",
    direccion: "1 avenida 9na. calle zona 14",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-san-judas-tadeo/",
    imagen: "ParqueSanJudasTadeo.jpg",
  },
  {
    zona: 19,
    parque: "Parque 10 de mayo",
    direccion:
      "5ta. calle entre 7ma. y 8va. avenida Colonia La Florida zona 19",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/parque-10-de-mayo/",
    imagen: "Parque10deMayo.jpg",
  },
  {
    zona: 21,
    parque: "Canchas Deportivas y Recreativas",
    direccion: "6ta. Calle B 4-40 zona 21",
    tipo: "Sistema de Parques y Áreas Verdes",
    link: "https://grandistritoverde.com.gt/park/canchas-deportivas/",
    imagen: "CanchasDeportivasyRecreativas.jpg",
  },
];
