import "./globals.css";
import localFont from "next/font/local";
import BackToTop from "./components/BackToTop";

export const metadata = {
  title: "250 años ciudad de Guatemala",
  description: "Generated by create next app",
};

const muni = localFont({
  src: [
    {
      path: "./fonts/Montserrat-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-muni",
});

/* Marcellus */
const MarcellusRegular = localFont({
  src: "./fonts/Marcellus-Regular.ttf"
});
export {MarcellusRegular}; 

/* Monsterrat */
const MontserratLightItalic = localFont({
  src: "./fonts/Montserrat-LightItalic.ttf"
});
export {MontserratLightItalic}; 

const MontserratSemiBoldItalic = localFont({
  src: "./fonts/Montserrat-SemiBoldItalic.ttf"
});
export {MontserratSemiBoldItalic}; 

const MontserratMediumItalic = localFont({
  src: "./fonts/Montserrat-MediumItalic.ttf"
});
export {MontserratMediumItalic}; 

const MontserratBlack3 = localFont({
  src: "./fonts/Montserrat-Black_3.ttf"
});
export {MontserratBlack3}; 

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <script src="https://gis.muniguate.com/accessibility-widget/widget.js" id="widgetScript" data-position="bottom-right" data-offsetx="20" data-offsety="20" data-primarycolor="#10069f"></script>
      <body className={`${muni.variable} font-muni`}>
        {children}
        <BackToTop />
      </body>
    </html>
  );
}

